// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:money_tracking/models/category.dart';
import 'package:money_tracking/models/planned_expense.dart';
import 'package:money_tracking/models/transaction.dart';
import 'package:money_tracking/models/transaction_type.dart';
import 'package:money_tracking/models/wallet.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(PlannedExpenseAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(WalletAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(PlannedExpenseAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(WalletAdapter());
  }
}
